version: '3'
services:
  app:
    container_name: docker_nodejsauth
    restart: always
    build: .
    ports:
      - 4001:4001
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - 27017:27017
